/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dekikurnia.rentalmobil.ui.main;

import com.dekikurnia.rentalmobil.model.Role;
import com.dekikurnia.rentalmobil.model.User;
import com.dekikurnia.rentalmobil.ui.master.KaryawanPanel;
import com.dekikurnia.rentalmobil.ui.master.PelangganPanel;
import com.dekikurnia.rentalmobil.ui.report.KaryawanReportPanel;
import com.dekikurnia.rentalmobil.ui.security.LoginDialog;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author deki kurnia
 */
public class FrameUtama extends javax.swing.JFrame {
    public static KaryawanReportPanel karyawanReportPanel;
    public static KaryawanPanel karyawanPanel;
    public static PelangganPanel pelangganPanel;
    JasperReport jasperReport;

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
        setExtendedState(FrameUtama.MAXIMIZED_BOTH);
        
    }
    
    public void showLoginPanel() {
        User user = new LoginDialog().login();
        constructMenu(user);
    }
    
    private void constructMenu(User user) {
        if (user.getRole() == Role.PEGAWAI) {
            menuMaster.setEnabled(false);
            menuLaporan.setEnabled(false);
        } else if (user.getRole() == Role.ADMIN) {
            menuTransaksi.setEnabled(true);
            menuLaporan.setEnabled(true);
            menuMaster.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuKaryawan = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPenyewaan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        dataKaryawan = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 212, 209));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(0, 254, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(51, 51, 255));
        menuBar.setBorder(null);
        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(51, 51, 255));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuKeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuKeluar.setText("Keluar");
        jMenu1.add(menuKeluar);

        menuBar.add(jMenu1);

        menuMaster.setBackground(new java.awt.Color(51, 51, 255));
        menuMaster.setForeground(new java.awt.Color(255, 255, 255));
        menuMaster.setText("Master");
        menuMaster.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuKaryawan.setText("Karyawan");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        menuMaster.add(menuKaryawan);

        menuPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        menuMaster.add(menuPelanggan);

        menuBar.add(menuMaster);

        menuTransaksi.setBackground(new java.awt.Color(51, 51, 255));
        menuTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        menuTransaksi.setText("Transaksi");
        menuTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuPenyewaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPenyewaan.setText("Penyewaan");
        menuTransaksi.add(menuPenyewaan);

        menuBar.add(menuTransaksi);

        menuLaporan.setBackground(new java.awt.Color(51, 51, 255));
        menuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporan.setText("Laporan");
        menuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        dataKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataKaryawan.setText("Data Karyawan");
        dataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataKaryawanActionPerformed(evt);
            }
        });
        menuLaporan.add(dataKaryawan);

        menuBar.add(menuLaporan);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        try {
            // TODO add your handling code here:
            if(karyawanPanel == null) {
                karyawanPanel = new KaryawanPanel();
                desktopPane.add(karyawanPanel);
            } else {
                karyawanPanel.toFront();
            }
            Dimension desktopSize = desktopPane.getSize();
            Dimension jInternalFrameSize = karyawanPanel.getSize();
            karyawanPanel.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
            karyawanPanel.setSelected(true);
            karyawanPanel.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        pelangganPanel = null;
        karyawanReportPanel = null;
        desktopPane.removeAll();
        desktopPane.updateUI();
        menuBar.updateUI();
        showLoginPanel();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void dataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataKaryawanActionPerformed
        try {
            // TODO add your handling code here:
            if (karyawanReportPanel == null) {
                karyawanReportPanel = new KaryawanReportPanel();
                desktopPane.add(karyawanReportPanel);
            } else {
                karyawanReportPanel.toFront();
            }
            karyawanReportPanel.setSize(desktopPane.getSize());
            karyawanReportPanel.setSelected(true);
            karyawanReportPanel.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_dataKaryawanActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        try {
            // TODO add your handling code here:
            if(pelangganPanel == null) {
                pelangganPanel = new PelangganPanel();
                desktopPane.add(pelangganPanel);
            } else {
                pelangganPanel.toFront();
            }
            Dimension desktopSize = desktopPane.getSize();
            Dimension jInternalFrameSize = pelangganPanel.getSize();
            pelangganPanel.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
            pelangganPanel.setSelected(true);
            pelangganPanel.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_menuPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataKaryawan;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPenyewaan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables

   
}
