/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dekikurnia.rentalmobil.ui.toolbar;

import javax.swing.JButton;

/**
 *
 * @author deki kurnia
 */
public class MasterToolbar extends javax.swing.JPanel {

    /**
     * Creates new form MasterToolbar
     */
    public MasterToolbar() {
        initComponents();
        kondisiAwal();
    }
    
    public JButton getButtonBatal() {
        return buttonBatal;
    }

    public JButton getButtonHapus() {
        return buttonHapus;
    }

    public JButton getButtonSimpan() {
        return buttonSimpan;
    }

    public JButton getButtonUbah() {
        return buttonUbah;
    }

    public JButton getButtonTambah() {
        return buttonTambah;
    }
    
    public void kondisiAwal() {
        buttonTambah.setEnabled(true);
        buttonSimpan.setEnabled(false);
        buttonUbah.setEnabled(false);
        buttonHapus.setEnabled(false);
        buttonBatal.setEnabled(false);
    }
    
    public void kondisiUbahOrHapus() {
        buttonTambah.setEnabled(false);
        buttonSimpan.setEnabled(false);
        buttonUbah.setEnabled(true);
        buttonHapus.setEnabled(true);
        buttonBatal.setEnabled(true);                
    }
    
    public void kondisiSimpan() {
        buttonTambah.setEnabled(false);
        buttonSimpan.setEnabled(true);
        buttonUbah.setEnabled(false);
        buttonHapus.setEnabled(false);
        buttonBatal.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTambah = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();

        buttonTambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonTambah.setText("Tambah");

        buttonSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSimpan.setText("Simpan");

        buttonBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonBatal.setText("Batal");

        buttonUbah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonUbah.setText("Ubah");

        buttonHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonHapus.setText("Hapus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(buttonUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    // End of variables declaration//GEN-END:variables
}
